# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@apollo/client-3.3.20" = {
      name = "_at_apollo_slash_client";
      packageName = "@apollo/client";
      version = "3.3.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@apollo/client/-/client-3.3.20.tgz";
        sha512 = "hS7UmBwJweudw/J3M0RAcusMHNiRuGqkRH6g91PM2ev8cXScIMdXr/++9jo7wD1nAITMCMF4HQQ3LFaw/Or0Bw==";
      };
    };
    "@babel/code-frame-7.14.5" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.14.5.tgz";
        sha512 = "9pzDqyc6OLDaqe+zbACgFkb6fKMNG6CObKpnYXChRsvYGyEdc7CA2BaqeOM+vOtCS5ndmJicPJhKAwYRI6UfFw==";
      };
    };
    "@babel/helper-validator-identifier-7.14.5" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.14.5.tgz";
        sha512 = "5lsetuxCLilmVGyiLEfoHBRX8UCFD+1m2x3Rj97WrW3V7H3u4RWRXA4evMjImCsin2J2YT0QaVDGf+z8ondbAg==";
      };
    };
    "@babel/highlight-7.14.5" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.14.5.tgz";
        sha512 = "qf9u2WFWVV0MppaL877j2dBtQIDgmidgjGk5VIMw3OadXvYaXn66U1BFlH2t4+t3i+8PhedppRv+i40ABzd+gg==";
      };
    };
    "@babel/runtime-7.14.6" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.14.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.14.6.tgz";
        sha512 = "/PCB2uJ7oM44tz8YhC4Z/6PeOKXp4K588f+5M3clr1M4zbqztlo0XEfJ2LEzj/FgwfgGcIdl8n7YYjTCI0BYwg==";
      };
    };
    "@graphql-typed-document-node/core-3.1.0" = {
      name = "_at_graphql-typed-document-node_slash_core";
      packageName = "@graphql-typed-document-node/core";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@graphql-typed-document-node/core/-/core-3.1.0.tgz";
        sha512 = "wYn6r8zVZyQJ6rQaALBEln5B1pzxb9shV5Ef97kTvn6yVGrqyXVnDqnU24MXnFubR+rZjBY9NWuxX3FB2sTsjg==";
      };
    };
    "@lit/reactive-element-1.0.0-rc.2" = {
      name = "_at_lit_slash_reactive-element";
      packageName = "@lit/reactive-element";
      version = "1.0.0-rc.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@lit/reactive-element/-/reactive-element-1.0.0-rc.2.tgz";
        sha512 = "cujeIl5Ei8FC7UHf4/4Q3bRJOtdTe1vpJV/JEBYCggedmQ+2P8A2oz7eE+Vxi6OJ4nc0X+KZxXnBoH4QrEbmEQ==";
      };
    };
    "@nodelib/fs.scandir-2.1.5" = {
      name = "_at_nodelib_slash_fs.scandir";
      packageName = "@nodelib/fs.scandir";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.5.tgz";
        sha512 = "vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==";
      };
    };
    "@nodelib/fs.stat-2.0.5" = {
      name = "_at_nodelib_slash_fs.stat";
      packageName = "@nodelib/fs.stat";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.5.tgz";
        sha512 = "RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==";
      };
    };
    "@nodelib/fs.walk-1.2.7" = {
      name = "_at_nodelib_slash_fs.walk";
      packageName = "@nodelib/fs.walk";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.7.tgz";
        sha512 = "BTIhocbPBSrRmHxOAJFtR18oLhxTtAFDAvL8hY1S3iU8k+E60W/YFs4jrixGzQjMpF4qPXxIQHcjVD9dz1C2QA==";
      };
    };
    "@trysound/sax-0.1.1" = {
      name = "_at_trysound_slash_sax";
      packageName = "@trysound/sax";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@trysound/sax/-/sax-0.1.1.tgz";
        sha512 = "Z6DoceYb/1xSg5+e+ZlPZ9v0N16ZvZ+wYMraFue4HYrE4ttONKtsvruIRf6t9TBR0YvSOfi1hUU0fJfBLCDYow==";
      };
    };
    "@types/parse-json-4.0.0" = {
      name = "_at_types_slash_parse-json";
      packageName = "@types/parse-json";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/parse-json/-/parse-json-4.0.0.tgz";
        sha512 = "//oorEZjL6sbPcKUaCdIGlIUeH26mgzimjBB77G6XRgnDl/L5wOnpyBGRe/Mmf5CVW3PwEBE1NjiMZ/ssFh4wA==";
      };
    };
    "@types/trusted-types-1.0.6" = {
      name = "_at_types_slash_trusted-types";
      packageName = "@types/trusted-types";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/trusted-types/-/trusted-types-1.0.6.tgz";
        sha512 = "230RC8sFeHoT6sSUlRO6a8cAnclO06eeiq1QDfiv2FGCLWFvvERWgwIQD4FWqD9A69BN7Lzee4OXwoMVnnsWDw==";
      };
    };
    "@types/zen-observable-0.8.2" = {
      name = "_at_types_slash_zen-observable";
      packageName = "@types/zen-observable";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/zen-observable/-/zen-observable-0.8.2.tgz";
        sha512 = "HrCIVMLjE1MOozVoD86622S7aunluLb2PJdPfb3nYiEtohm8mIB/vyv0Fd37AdeMFrTUQXEunw78YloMA3Qilg==";
      };
    };
    "@videojs/http-streaming-2.8.2" = {
      name = "_at_videojs_slash_http-streaming";
      packageName = "@videojs/http-streaming";
      version = "2.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@videojs/http-streaming/-/http-streaming-2.8.2.tgz";
        sha512 = "OU+KwB7I76j29NplHGg1Q1wtneOLA0nhjwUrdhoBJmo8dmqZO5TOMqPfhqfFZ4E8zJP9wXNLyRbhmesVqYMwmQ==";
      };
    };
    "@videojs/vhs-utils-3.0.2" = {
      name = "_at_videojs_slash_vhs-utils";
      packageName = "@videojs/vhs-utils";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@videojs/vhs-utils/-/vhs-utils-3.0.2.tgz";
        sha512 = "r8Yas1/tNGsGRNoIaDJuiWiQgM0P2yaEnobgzw5JcBiEqxnS8EXoUm4QtKH7nJtnppZ1yqBx1agBZCvBMKXA2w==";
      };
    };
    "@videojs/xhr-2.5.1" = {
      name = "_at_videojs_slash_xhr";
      packageName = "@videojs/xhr";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@videojs/xhr/-/xhr-2.5.1.tgz";
        sha512 = "wV9nGESHseSK+S9ePEru2+OJZ1jq/ZbbzniGQ4weAmTIepuBMSYPx5zrxxQA0E786T5ykpO8ts+LayV+3/oI2w==";
      };
    };
    "@wry/context-0.6.0" = {
      name = "_at_wry_slash_context";
      packageName = "@wry/context";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@wry/context/-/context-0.6.0.tgz";
        sha512 = "sAgendOXR8dM7stJw3FusRxFHF/ZinU0lffsA2YTyyIOfic86JX02qlPqPVqJNZJPAxFt+2EE8bvq6ZlS0Kf+Q==";
      };
    };
    "@wry/equality-0.5.1" = {
      name = "_at_wry_slash_equality";
      packageName = "@wry/equality";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@wry/equality/-/equality-0.5.1.tgz";
        sha512 = "FZKbdpbcVcbDxQrKcaBClNsQaMg9nof1RKM7mReJe5DKUzM5u8S7T+PqwNqvib5O2j2xxF1R4p5O3+b6baTrbw==";
      };
    };
    "@wry/trie-0.3.0" = {
      name = "_at_wry_slash_trie";
      packageName = "@wry/trie";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@wry/trie/-/trie-0.3.0.tgz";
        sha512 = "Yw1akIogPhAT6XPYsRHlZZIS0tIGmAl9EYXHi2scf7LPKKqdqmow/Hu4kEqP2cJR3EjaU/9L0ZlAjFf3hFxmug==";
      };
    };
    "aes-decrypter-3.1.2" = {
      name = "aes-decrypter";
      packageName = "aes-decrypter";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/aes-decrypter/-/aes-decrypter-3.1.2.tgz";
        sha512 = "42nRwfQuPRj9R1zqZBdoxnaAmnIFyDi0MNyTVhjdFOd8fifXKKRfwIHIZ6AMn1or4x5WONzjwRTbTWcsIQ0O4A==";
      };
    };
    "alphanum-sort-1.0.2" = {
      name = "alphanum-sort";
      packageName = "alphanum-sort";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/alphanum-sort/-/alphanum-sort-1.0.2.tgz";
        sha1 = "97a1119649b211ad33691d9f9f486a8ec9fbe0a3";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "any-promise-1.3.0" = {
      name = "any-promise";
      packageName = "any-promise";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/any-promise/-/any-promise-1.3.0.tgz";
        sha1 = "abc6afeedcea52e809cdc0376aed3ce39635d17f";
      };
    };
    "array-union-2.1.0" = {
      name = "array-union";
      packageName = "array-union";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-union/-/array-union-2.1.0.tgz";
        sha512 = "HGyxoOTYUyCM6stUe6EJgnd4EoewAI7zMdfqO+kGjnlZmBDz/cR5pf8r/cR4Wq60sL/p0IkcjUEEPwS3GFrIyw==";
      };
    };
    "async-0.2.10" = {
      name = "async";
      packageName = "async";
      version = "0.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.2.10.tgz";
        sha1 = "b6bbe0b0674b9d719708ca38de8c237cb526c3d1";
      };
    };
    "autoprefixer-10.2.6" = {
      name = "autoprefixer";
      packageName = "autoprefixer";
      version = "10.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/autoprefixer/-/autoprefixer-10.2.6.tgz";
        sha512 = "8lChSmdU6dCNMCQopIf4Pe5kipkAGj/fvTMslCsih0uHpOrXOPUEVOmYMMqmw3cekQkSD7EhIeuYl5y0BLdKqg==";
      };
    };
    "backo2-1.0.2" = {
      name = "backo2";
      packageName = "backo2";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/backo2/-/backo2-1.0.2.tgz";
        sha1 = "31ab1ac8b129363463e35b3ebb69f4dfcfba7947";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "boolbase-1.0.0" = {
      name = "boolbase";
      packageName = "boolbase";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
        sha1 = "68dff5fbe60c51eb37725ea9e3ed310dcc1e776e";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "browserslist-4.16.6" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.16.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.16.6.tgz";
        sha512 = "Wspk/PqO+4W9qp5iUTJsa1B/QrYn1keNCcEP5OvP7WBwT4KaDly0uONYmC6Xa3Z5IqnUgS0KcgLYu1l74x0ZXQ==";
      };
    };
    "callsites-3.1.0" = {
      name = "callsites";
      packageName = "callsites";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsites/-/callsites-3.1.0.tgz";
        sha512 = "P8BjAsXvZS+VIDUI11hHCQEv74YT67YUi5JJFNWIqL235sBmjX4+qx9Muvls5ivyNENctx46xQLQ3aTuE7ssaQ==";
      };
    };
    "camelcase-1.2.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz";
        sha1 = "9bb5304d2e0b56698b2c758b08a3eaa9daa58a39";
      };
    };
    "caniuse-api-3.0.0" = {
      name = "caniuse-api";
      packageName = "caniuse-api";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-api/-/caniuse-api-3.0.0.tgz";
        sha512 = "bsTwuIg/BZZK/vreVTYYbSWoe2F+71P7K5QGEX+pT250DZbfU1MQ5prOKpPR+LL6uWKK3KMwMCAS74QB3Um1uw==";
      };
    };
    "caniuse-lite-1.0.30001239" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001239";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001239.tgz";
        sha512 = "cyBkXJDMeI4wthy8xJ2FvDU6+0dtcZSJW3voUF8+e9f1bBeuvyZfc3PNbkOETyhbR+dGCPzn9E7MA3iwzusOhQ==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "chalk-4.1.1" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.1.tgz";
        sha512 = "diHzdDKxcU+bAsUboHLPEDQiw0qEe0qd7SYUn3HgcFlWgbDcfLGswOHYeGrHKzG9z6UYf01d9VFMfZxPM1xZSg==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "colord-2.0.1" = {
      name = "colord";
      packageName = "colord";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/colord/-/colord-2.0.1.tgz";
        sha512 = "vm5YpaWamD0Ov6TSG0GGmUIwstrWcfKQV/h2CmbR7PbNu41+qdB5PW9lpzhjedrpm08uuYvcXi0Oel1RLZIJuA==";
      };
    };
    "colorette-1.2.2" = {
      name = "colorette";
      packageName = "colorette";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorette/-/colorette-1.2.2.tgz";
        sha512 = "MKGMzyfeuutC/ZJ1cba9NqcNpfeqMUcYmyF1ZFY6/Cn7CNSAKx6a+s48sqLqyAiZuaP2TcqMhoo+dlwFnVxT9w==";
      };
    };
    "commander-7.2.0" = {
      name = "commander";
      packageName = "commander";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-7.2.0.tgz";
        sha512 = "QrWXB+ZQSVPmIWIhtEO9H+gwHaMGYiF5ChvoJ+K9ZGHG/sVsa6yiesAD1GC/x46sET00Xlwo1u49RVVVzvcSkw==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "concat-with-sourcemaps-1.1.0" = {
      name = "concat-with-sourcemaps";
      packageName = "concat-with-sourcemaps";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-with-sourcemaps/-/concat-with-sourcemaps-1.1.0.tgz";
        sha512 = "4gEjHJFT9e+2W/77h/DS5SGUgwDaOwprX8L/gl5+3ixnzkVJJsZWDSelmN3Oilw3LNDZjZV0yqH1hLG3k6nghg==";
      };
    };
    "cosmiconfig-7.0.0" = {
      name = "cosmiconfig";
      packageName = "cosmiconfig";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cosmiconfig/-/cosmiconfig-7.0.0.tgz";
        sha512 = "pondGvTuVYDk++upghXJabWzL6Kxu6f26ljFw64Swq9v6sQPUL3EUlVDV56diOjpCayKihL6hVe8exIACU4XcA==";
      };
    };
    "css-color-names-0.0.4" = {
      name = "css-color-names";
      packageName = "css-color-names";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-color-names/-/css-color-names-0.0.4.tgz";
        sha1 = "808adc2e79cf84738069b646cb20ec27beb629e0";
      };
    };
    "css-color-names-1.0.1" = {
      name = "css-color-names";
      packageName = "css-color-names";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-color-names/-/css-color-names-1.0.1.tgz";
        sha512 = "/loXYOch1qU1biStIFsHH8SxTmOseh1IJqFvy8IujXOm1h+QjUdDhkzOrR5HG8K8mlxREj0yfi8ewCHx0eMxzA==";
      };
    };
    "css-declaration-sorter-6.0.3" = {
      name = "css-declaration-sorter";
      packageName = "css-declaration-sorter";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-declaration-sorter/-/css-declaration-sorter-6.0.3.tgz";
        sha512 = "52P95mvW1SMzuRZegvpluT6yEv0FqQusydKQPZsNN5Q7hh8EwQvN8E2nwuJ16BBvNN6LcoIZXu/Bk58DAhrrxw==";
      };
    };
    "css-select-3.1.2" = {
      name = "css-select";
      packageName = "css-select";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select/-/css-select-3.1.2.tgz";
        sha512 = "qmss1EihSuBNWNNhHjxzxSfJoFBM/lERB/Q4EnsJQQC62R2evJDW481091oAdOr9uh46/0n4nrg0It5cAnj1RA==";
      };
    };
    "css-tree-1.1.3" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-1.1.3.tgz";
        sha512 = "tRpdppF7TRazZrjJ6v3stzv93qxRcSsFmW6cX0Zm2NVKpxE1WV1HblnghVv9TreireHkqI/VDEsfolRF1p6y7Q==";
      };
    };
    "css-what-4.0.0" = {
      name = "css-what";
      packageName = "css-what";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-4.0.0.tgz";
        sha512 = "teijzG7kwYfNVsUh2H/YN62xW3KK9YhXEgSlbxMlcyjPNvdKJqFx5lrwlJgoFP1ZHlB89iGDlo/JyshKeRhv5A==";
      };
    };
    "cssesc-3.0.0" = {
      name = "cssesc";
      packageName = "cssesc";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz";
        sha512 = "/Tb/JcjK111nNScGob5MNtsntNM1aCNUDipB/TkwZFhyDrrE47SOx/18wF2bbjgc3ZzCSKW1T5nt5EbFoAz/Vg==";
      };
    };
    "cssnano-5.0.6" = {
      name = "cssnano";
      packageName = "cssnano";
      version = "5.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano/-/cssnano-5.0.6.tgz";
        sha512 = "NiaLH/7yqGksFGsFNvSRe2IV/qmEBAeDE64dYeD8OBrgp6lE8YoMeQJMtsv5ijo6MPyhuoOvFhI94reahBRDkw==";
      };
    };
    "cssnano-preset-default-5.1.3" = {
      name = "cssnano-preset-default";
      packageName = "cssnano-preset-default";
      version = "5.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-preset-default/-/cssnano-preset-default-5.1.3.tgz";
        sha512 = "qo9tX+t4yAAZ/yagVV3b+QBKeLklQbmgR3wI7mccrDcR+bEk9iHgZN1E7doX68y9ThznLya3RDmR+nc7l6/2WQ==";
      };
    };
    "cssnano-utils-2.0.1" = {
      name = "cssnano-utils";
      packageName = "cssnano-utils";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-utils/-/cssnano-utils-2.0.1.tgz";
        sha512 = "i8vLRZTnEH9ubIyfdZCAdIdgnHAUeQeByEeQ2I7oTilvP9oHO6RScpeq3GsFUVqeB8uZgOQ9pw8utofNn32hhQ==";
      };
    };
    "csso-4.2.0" = {
      name = "csso";
      packageName = "csso";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/csso/-/csso-4.2.0.tgz";
        sha512 = "wvlcdIbf6pwKEk7vHj8/Bkc0B4ylXZruLvOgs9doS5eOsOpuodOV2zJChSpkp+pRpYQLQMeF04nr3Z68Sta9jA==";
      };
    };
    "cuint-0.2.2" = {
      name = "cuint";
      packageName = "cuint";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cuint/-/cuint-0.2.2.tgz";
        sha1 = "408086d409550c2631155619e9fa7bcadc3b991b";
      };
    };
    "debug-4.3.1" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.1.tgz";
        sha512 = "doEwdvm4PCeK4K3RQN2ZC2BYUBaxwLARCqZmMjtF8a51J2Rb0xpVloFRnCODwqjpwnAoao4pelN8l3RJdv3gRQ==";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "dir-glob-3.0.1" = {
      name = "dir-glob";
      packageName = "dir-glob";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dir-glob/-/dir-glob-3.0.1.tgz";
        sha512 = "WkrWp9GR4KXfKGYzOLmTuGVi1UWFfws377n9cc55/tb6DuqyF6pcQ5AbiHEshaDpY9v6oaSr2XCDidGmMwdzIA==";
      };
    };
    "dom-serializer-1.3.2" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-1.3.2.tgz";
        sha512 = "5c54Bk5Dw4qAxNOI1pFEizPSjVsx5+bpJKmL2kPn8JhBUq2q09tTCa3mjijun2NfK78NMouDYNMBkOrPZiS+ig==";
      };
    };
    "dom-walk-0.1.2" = {
      name = "dom-walk";
      packageName = "dom-walk";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-walk/-/dom-walk-0.1.2.tgz";
        sha512 = "6QvTW9mrGeIegrFXdtQi9pk7O/nSK6lSdXW2eqUspN5LWD7UTji2Fqw5V2YLjBpHEoU9Xl/eUWNpDeZvoyOv2w==";
      };
    };
    "domelementtype-2.2.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.2.0.tgz";
        sha512 = "DtBMo82pv1dFtUmHyr48beiuq792Sxohr+8Hm9zoxklYPfa6n0Z3Byjj2IV7bmr2IyqClnqEQhfgHJJ5QF0R5A==";
      };
    };
    "domhandler-4.2.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-4.2.0.tgz";
        sha512 = "zk7sgt970kzPks2Bf+dwT/PLzghLnsivb9CcxkvR8Mzr66Olr0Ofd8neSbglHJHaHa2MadfoSdNlKYAaafmWfA==";
      };
    };
    "domutils-2.7.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-2.7.0.tgz";
        sha512 = "8eaHa17IwJUPAiB+SoTYBo5mCdeMgdcAoXJ59m6DT1vw+5iLS3gNoqYaRowaBKtGVrOF1Jz4yDTgYKLK2kvfJg==";
      };
    };
    "dotenv-10.0.0" = {
      name = "dotenv";
      packageName = "dotenv";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dotenv/-/dotenv-10.0.0.tgz";
        sha512 = "rlBi9d8jpv9Sf1klPjNfFAuWDjKLwTIJJ/VxtoTwIR6hnZxcEOQCZg2oIL3MWBYw5GpUDKOEnND7LXTbIpQ03Q==";
      };
    };
    "electron-to-chromium-1.3.756" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.3.756";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.3.756.tgz";
        sha512 = "WsmJym1TMeHVndjPjczTFbnRR/c4sbzg8fBFtuhlb2Sru3i/S1VGpzDSrv/It8ctMU2bj8G7g7/O3FzYMGw6eA==";
      };
    };
    "entities-2.2.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.2.0.tgz";
        sha512 = "p92if5Nz619I0w+akJrLZH0MX0Pb5DX39XOwQTtXSdQQOaYH03S1uIQp4mhOZtAXrxq4ViO67YTiLBo2638o9A==";
      };
    };
    "error-ex-1.3.2" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.2.tgz";
        sha512 = "7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==";
      };
    };
    "esbuild-0.12.9" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.12.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.12.9.tgz";
        sha512 = "MWRhAbMOJ9RJygCrt778rz/qNYgA4ZVj6aXnNPxFjs7PmIpb0fuB9Gmg5uWrr6n++XKwwm/RmSz6RR5JL2Ocsw==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esmarked-2.1.1" = {
      name = "esmarked";
      packageName = "esmarked";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esmarked/-/esmarked-2.1.1.tgz";
        sha512 = "J6gJvL71+qV/wpNJzSszR/atMl/AEpZvDIhlfKOWGkVm5c7vw9wcLYAdUMvoKq+ogxgD17zyvHhOiCTKTYZhbg==";
      };
    };
    "eventemitter3-3.1.2" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-3.1.2.tgz";
        sha512 = "tvtQIeLVHjDkJYnzf2dgVMxfuSGJeM/7UCG17TT4EumTfNtF+0nebF/4zWOIkCreAbtNqhGEboB6BWrwqNaw4Q==";
      };
    };
    "fast-glob-3.2.5" = {
      name = "fast-glob";
      packageName = "fast-glob";
      version = "3.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-glob/-/fast-glob-3.2.5.tgz";
        sha512 = "2DtFcgT68wiTTiwZ2hNdJfcHNke9XOfnwmBRWXhmeKM8rF0TGwmC/Qto3S7RoZKp5cilZbxzO5iTNTQsJ+EeDg==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "fastq-1.11.0" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.11.0.tgz";
        sha512 = "7Eczs8gIPDrVzT+EksYBcupqMyxSHXXrHOLRRxU2/DicV8789MRBRR8+Hc2uWzUupOs4YS4JzBmBxjjCVBxD/g==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "fraction.js-4.1.1" = {
      name = "fraction.js";
      packageName = "fraction.js";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fraction.js/-/fraction.js-4.1.1.tgz";
        sha512 = "MHOhvvxHTfRFpF1geTK9czMIZ6xclsEor2wkIGYYq+PxcQqT7vStJqjhe6S1TenZrMZzo+wlqOufBDVepUEgPg==";
      };
    };
    "fs-extra-0.26.7" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "0.26.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-0.26.7.tgz";
        sha1 = "9ae1fdd94897798edab76d0918cf42d0c3184fa9";
      };
    };
    "fs-extra-10.0.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-10.0.0.tgz";
        sha512 = "C5owb14u9eJwizKGdchcDUQeFtlSHHthBk8pbX9Vc1PFZrLombudjDnNns88aYslCyF6IY5SUw3Roz6xShcEIQ==";
      };
    };
    "fs-promise-0.5.0" = {
      name = "fs-promise";
      packageName = "fs-promise";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-promise/-/fs-promise-0.5.0.tgz";
        sha1 = "4347d6bf624655a7061a4319213c393276ad3ef3";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "glob-7.1.7" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.7.tgz";
        sha512 = "OvD9ENzPLbegENnYP5UUfJIirTg4+XwMWGaQfQTY0JenxNvvIKP3U3/tAQSPIu/lHxXYSZmpXlUHeqAIdKzBLQ==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "global-4.4.0" = {
      name = "global";
      packageName = "global";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/global/-/global-4.4.0.tgz";
        sha512 = "wv/LAoHdRE3BeTGz53FAamhGlPLhlssK45usmGFThIi4XqnBmjKQ16u+RNbP7WvigRZDxUsM0J3gcQ5yicaL0w==";
      };
    };
    "globby-11.0.4" = {
      name = "globby";
      packageName = "globby";
      version = "11.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/globby/-/globby-11.0.4.tgz";
        sha512 = "9O4MVG9ioZJ08ffbcyVYyLOJLk5JQ688pJ4eMGLpdWLHq/Wr1D9BlriLQyL0E+jbkuePVZXYFj47QM/v093wHg==";
      };
    };
    "graceful-fs-4.2.6" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.6.tgz";
        sha512 = "nTnJ528pbqxYanhpDYsi4Rd8MAeaBA67+RZ10CM1m3bTAVFEDcd5AuA4a6W5YkGZ1iNXHzZz8T6TBKLeBuNriQ==";
      };
    };
    "graphql-15.5.1" = {
      name = "graphql";
      packageName = "graphql";
      version = "15.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql/-/graphql-15.5.1.tgz";
        sha512 = "FeTRX67T3LoE3LWAxxOlW2K3Bz+rMYAC18rRguK4wgXaTZMiJwSUwDmPFo3UadAKbzirKIg5Qy+sNJXbpPRnQw==";
      };
    };
    "graphql-tag-2.12.4" = {
      name = "graphql-tag";
      packageName = "graphql-tag";
      version = "2.12.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql-tag/-/graphql-tag-2.12.4.tgz";
        sha512 = "VV1U4O+9x99EkNpNmCUV5RZwq6MnK4+pGbRYWG+lA/m3uo7TSqJF81OkcOP148gFP6fzdl7JWYBrwWVTS9jXww==";
      };
    };
    "grunt-contrib-uglify-0.2.7" = {
      name = "grunt-contrib-uglify";
      packageName = "grunt-contrib-uglify";
      version = "0.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-uglify/-/grunt-contrib-uglify-0.2.7.tgz";
        sha1 = "e6bda51e0c40a1459f6cead423c65efd725a1bf7";
      };
    };
    "grunt-lib-contrib-0.6.1" = {
      name = "grunt-lib-contrib";
      packageName = "grunt-lib-contrib";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-lib-contrib/-/grunt-lib-contrib-0.6.1.tgz";
        sha1 = "3f56adb7da06e814795ee2415b0ebe5fb8903ebb";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "hex-color-regex-1.1.0" = {
      name = "hex-color-regex";
      packageName = "hex-color-regex";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hex-color-regex/-/hex-color-regex-1.1.0.tgz";
        sha512 = "l9sfDFsuqtOqKDsQdqrMRk0U85RZc0RtOR9yPI7mRVOa4FsR/BVnZ0shmQRM96Ji99kYZP/7hn1cedc1+ApsTQ==";
      };
    };
    "hoist-non-react-statics-3.3.2" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-3.3.2.tgz";
        sha512 = "/gGivxi8JPKWNm/W0jSmzcMPpfpPLc3dY/6GxhX2hQ9iGj3aDfklV4ET7NjKpSinLpJ5vafa9iiGIEZg10SfBw==";
      };
    };
    "hsl-regex-1.0.0" = {
      name = "hsl-regex";
      packageName = "hsl-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hsl-regex/-/hsl-regex-1.0.0.tgz";
        sha1 = "d49330c789ed819e276a4c0d272dffa30b18fe6e";
      };
    };
    "hsla-regex-1.0.0" = {
      name = "hsla-regex";
      packageName = "hsla-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hsla-regex/-/hsla-regex-1.0.0.tgz";
        sha1 = "c1ce7a3168c8c6614033a4b5f7877f3b225f9c38";
      };
    };
    "html-prettify-1.0.3" = {
      name = "html-prettify";
      packageName = "html-prettify";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-prettify/-/html-prettify-1.0.3.tgz";
        sha512 = "tbgHB/cFIAxqDW/wryyGEnd396qOtJIBf4q29kW2jdJy1Q7GYKl1LnoI28cKzMJG9UYZx0RGkUKTRMl0b6YZNg==";
      };
    };
    "ignore-5.1.8" = {
      name = "ignore";
      packageName = "ignore";
      version = "5.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-5.1.8.tgz";
        sha512 = "BMpfD7PpiETpBl/A6S498BaIJ6Y/ABT93ETbby2fP00v4EbvPBXWEoaR1UBPKs3iR53pJY7EtZk5KACI57i1Uw==";
      };
    };
    "import-fresh-3.3.0" = {
      name = "import-fresh";
      packageName = "import-fresh";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-fresh/-/import-fresh-3.3.0.tgz";
        sha512 = "veYYhQa+D1QBKznvhUHxb8faxlrwUnxseDAbAp457E0wLNio2bOSKnjYDhMj+YiAq61xrMGhQk9iXVk5FzgQMw==";
      };
    };
    "individual-2.0.0" = {
      name = "individual";
      packageName = "individual";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/individual/-/individual-2.0.0.tgz";
        sha1 = "833b097dad23294e76117a98fb38e0d9ad61bb97";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-absolute-url-3.0.3" = {
      name = "is-absolute-url";
      packageName = "is-absolute-url";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-absolute-url/-/is-absolute-url-3.0.3.tgz";
        sha512 = "opmNIX7uFnS96NtPmhWQgQx6/NYFgsUXYMllcfzwWKUMwfo8kku1TvE6hkNcH+Q1ts5cMVrsY7j0bxXQDciu9Q==";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "is-color-stop-1.1.0" = {
      name = "is-color-stop";
      packageName = "is-color-stop";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-color-stop/-/is-color-stop-1.1.0.tgz";
        sha1 = "cfff471aee4dd5c9e158598fbe12967b5cdad345";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha1 = "a88c02535791f02ed37c76a1b9ea9773c833f8c2";
      };
    };
    "is-function-1.0.2" = {
      name = "is-function";
      packageName = "is-function";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-function/-/is-function-1.0.2.tgz";
        sha512 = "lw7DUp0aWXYg+CBCN+JKkcE0Q2RayZnSvnZBlwgxHBQhqt5pZNVy4Ri7H9GmmXkdu7LUthszM+Tor1u/2iBcpQ==";
      };
    };
    "is-glob-4.0.1" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.1.tgz";
        sha512 = "5G0tKtBTFImOqDnLB2hG6Bp2qcKEFduo4tZu9MT/H6NQv/ghhy30o55ufafxJ/LdH79LLs2Kfrn85TLKyA7BUg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-resolvable-1.1.0" = {
      name = "is-resolvable";
      packageName = "is-resolvable";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-resolvable/-/is-resolvable-1.1.0.tgz";
        sha512 = "qgDYXFSR5WvEfuS5dMj6oTMEbrrSaM0CrFk2Yiq/gXnBvD9pMa2jGXxyhGLfvhZpuMZe18CJpFxAt3CRs42NMg==";
      };
    };
    "iterall-1.3.0" = {
      name = "iterall";
      packageName = "iterall";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/iterall/-/iterall-1.3.0.tgz";
        sha512 = "QZ9qOMdF+QLHxy1QIpUHUU1D5pS2CG2P69LF6L6CPjPYA/XMOmKV3PZpawHoAjHNyB0swdVTRxdYT4tbBbxqwg==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "json-parse-even-better-errors-2.3.1" = {
      name = "json-parse-even-better-errors";
      packageName = "json-parse-even-better-errors";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-even-better-errors/-/json-parse-even-better-errors-2.3.1.tgz";
        sha512 = "xyFwyhro/JEof6Ghe2iz2NcXoj2sloNsWr/XsERDK/oiPCfaNhl5ONfp+jQdAZRQQ0IJWNzH9zIZF7li91kh2w==";
      };
    };
    "jsonfile-2.4.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-2.4.0.tgz";
        sha1 = "3736a2b428b87bbda0cc83b53fa3d633a35c2ae8";
      };
    };
    "jsonfile-6.1.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.1.0.tgz";
        sha512 = "5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==";
      };
    };
    "karma-safaritechpreview-launcher-0.0.6" = {
      name = "karma-safaritechpreview-launcher";
      packageName = "karma-safaritechpreview-launcher";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/karma-safaritechpreview-launcher/-/karma-safaritechpreview-launcher-0.0.6.tgz";
        sha512 = "2QMxAGXPQ37H3KoR9SCdh0OoktQZ5MyrxkvBiZ+VVOQfYVrcyOQXGrPea0/DKvf8qoQvrvP2FHcP/BxsuxuyHw==";
      };
    };
    "keycode-2.2.0" = {
      name = "keycode";
      packageName = "keycode";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keycode/-/keycode-2.2.0.tgz";
        sha1 = "3d0af56dc7b8b8e5cba8d0a97f107204eec22b04";
      };
    };
    "klaw-1.3.1" = {
      name = "klaw";
      packageName = "klaw";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/klaw/-/klaw-1.3.1.tgz";
        sha1 = "4088433b46b3b1ba259d78785d8e96f73ba02439";
      };
    };
    "lines-and-columns-1.1.6" = {
      name = "lines-and-columns";
      packageName = "lines-and-columns";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-1.1.6.tgz";
        sha1 = "1c00c743b433cd0a4e80758f7b64a57440d9ff00";
      };
    };
    "lit-2.0.0-rc.2" = {
      name = "lit";
      packageName = "lit";
      version = "2.0.0-rc.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lit/-/lit-2.0.0-rc.2.tgz";
        sha512 = "BOCuoJR04WaTV8UqTKk09cNcQA10Aq2LCcBOiHuF7TzWH5RNDsbCBP5QM9sLBSotGTXbDug/gFO08jq6TbyEtw==";
      };
    };
    "lit-element-3.0.0-rc.2" = {
      name = "lit-element";
      packageName = "lit-element";
      version = "3.0.0-rc.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lit-element/-/lit-element-3.0.0-rc.2.tgz";
        sha512 = "2Z7DabJ3b5K+p5073vFjMODoaWqy5PIaI4y6ADKm+fCGc8OnX9fU9dMoUEBZjFpd/bEFR9PBp050tUtBnT9XTQ==";
      };
    };
    "lit-html-2.0.0-rc.3" = {
      name = "lit-html";
      packageName = "lit-html";
      version = "2.0.0-rc.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lit-html/-/lit-html-2.0.0-rc.3.tgz";
        sha512 = "Y6P8LlAyQuqvzq6l/Nc4z5/P5M/rVLYKQIRxcNwSuGajK0g4kbcBFQqZmgvqKG+ak+dHZjfm2HUw9TF5N/pkCw==";
      };
    };
    "lit-ntml-2.18.2" = {
      name = "lit-ntml";
      packageName = "lit-ntml";
      version = "2.18.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lit-ntml/-/lit-ntml-2.18.2.tgz";
        sha512 = "5jJwlcFvamwzv55HFpNXpYTJRTXKpkLXZrr4gh+Vkj+3VrjbdpMOgZSKHpNZ5j/uVccEYTadM34UR9k++94lDw==";
      };
    };
    "lodash.memoize-4.1.2" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-4.1.2.tgz";
        sha1 = "bcc6c49a42a2840ed997f323eada5ecd182e0bfe";
      };
    };
    "lodash.uniq-4.5.0" = {
      name = "lodash.uniq";
      packageName = "lodash.uniq";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.uniq/-/lodash.uniq-4.5.0.tgz";
        sha1 = "d0225373aeb652adc1bc82e4945339a842754773";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "m3u8-parser-4.7.0" = {
      name = "m3u8-parser";
      packageName = "m3u8-parser";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/m3u8-parser/-/m3u8-parser-4.7.0.tgz";
        sha512 = "48l/OwRyjBm+QhNNigEEcRcgbRvnUjL7rxs597HmW9QSNbyNvt+RcZ9T/d9vxi9A9z7EZrB1POtZYhdRlwYQkQ==";
      };
    };
    "make-dir-3.1.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-3.1.0.tgz";
        sha512 = "g3FeP20LNwhALb/6Cz6Dd4F2ngze0jz7tbzrD2wAV+o9FeNHe4rL+yK2md0J/fiSf1sa1ADhXqi5+oVwOM/eGw==";
      };
    };
    "marcosc-async-3.0.5" = {
      name = "marcosc-async";
      packageName = "marcosc-async";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/marcosc-async/-/marcosc-async-3.0.5.tgz";
        sha1 = "41e6d56c656c811859d34b97a0a26093f71dc360";
      };
    };
    "mdn-data-2.0.14" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.14.tgz";
        sha512 = "dn6wd0uw5GsdswPFfsgMp5NSB0/aDe6fK94YJV/AJDYXL6HVLWBsxeq7js7Ad+mU2K9LAlwpk6kN2D5mwCPVow==";
      };
    };
    "merge2-1.4.1" = {
      name = "merge2";
      packageName = "merge2";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge2/-/merge2-1.4.1.tgz";
        sha512 = "8q7VEgMJW4J8tcfVPy8g09NcQwZdbwFEqhe/WZkoIzjn/3TGDwtOCYtXGxA3O8tPzpczCCDgv+P2P5y00ZJOOg==";
      };
    };
    "micromatch-4.0.4" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.4.tgz";
        sha512 = "pRmzw/XUcwXGpD9aI9q/0XOwLNygjETJ8y0ao0wdqprrzDa4YnxLcz7fQRZr8voh8V10kGhABbNcHVk5wHgWwg==";
      };
    };
    "mime-2.5.2" = {
      name = "mime";
      packageName = "mime";
      version = "2.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-2.5.2.tgz";
        sha512 = "tqkh47FzKeCPD2PUiPB6pkbMzsCasjxAfC62/Wap5qrUWcb+sFasXUC5I3gYM5iBM8v/Qpn4UK0x+j0iHyFPDg==";
      };
    };
    "min-document-2.19.0" = {
      name = "min-document";
      packageName = "min-document";
      version = "2.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/min-document/-/min-document-2.19.0.tgz";
        sha1 = "7bd282e3f5842ed295bb748cdd9f1ffa2c824685";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "mpd-parser-0.16.0" = {
      name = "mpd-parser";
      packageName = "mpd-parser";
      version = "0.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mpd-parser/-/mpd-parser-0.16.0.tgz";
        sha512 = "/pOFsDbOxXFAla47rYMdIypBZVtsQ9q3OHNuKtW2CJMaCGtNDtUcLS+B2TToYmB20rgi3XIgkyc2EsIvIAS4NA==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "mux.js-5.11.0" = {
      name = "mux.js";
      packageName = "mux.js";
      version = "5.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mux.js/-/mux.js-5.11.0.tgz";
        sha512 = "Q/iLfohHh5Pp6lW7EFtcxNuaCNJ3Ruywfy46pWLsY+yIxR1kXXImYY1wOhg8jLdBMs1kRaZqsiB4Zncsiw0a2Q==";
      };
    };
    "mz-2.7.0" = {
      name = "mz";
      packageName = "mz";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mz/-/mz-2.7.0.tgz";
        sha512 = "z81GNO7nnYMEhrGh9LeymoE4+Yr0Wn5McHIZMK5cfQCl+NDX08sCZgUc9/6MHni9IWuFLm1Z3HTCXu2z9fN62Q==";
      };
    };
    "nanoid-3.1.23" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.1.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.1.23.tgz";
        sha512 = "FiB0kzdP0FFVGDKlRLEQ1BgDzU87dy5NnzjeW9YZNt+/c3+q82EQDUwniSAUxp/F0gFNI1ZhKU1FqYsMuqZVnw==";
      };
    };
    "node-releases-1.1.73" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "1.1.73";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-1.1.73.tgz";
        sha512 = "uW7fodD6pyW2FZNZnp/Z3hvWKeEW1Y8R1+1CnErE8cXFXzl5blBOoVB41CvMer6P6Q0S5FXDwcHgFd1Wj0U9zg==";
      };
    };
    "normalize-range-0.1.2" = {
      name = "normalize-range";
      packageName = "normalize-range";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-range/-/normalize-range-0.1.2.tgz";
        sha1 = "2d10c06bdfd312ea9777695a4d28439456b75942";
      };
    };
    "normalize-url-6.1.0" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-6.1.0.tgz";
        sha512 = "DlL+XwOy3NxAQ8xuC0okPgK46iuVNAK01YN7RueYBqqFeGsBjV9XmCAzAdgt+667bCl5kPh9EqKKDwnaPG1I7A==";
      };
    };
    "nth-check-2.0.0" = {
      name = "nth-check";
      packageName = "nth-check";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nth-check/-/nth-check-2.0.0.tgz";
        sha512 = "i4sc/Kj8htBrAiH1viZ0TgU8Y5XqCaV/FziYK6TBczxmeKm3AEFWqqF3195yKudrarqy7Zu80Ra5dobFjn9X/Q==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "optimism-0.16.1" = {
      name = "optimism";
      packageName = "optimism";
      version = "0.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimism/-/optimism-0.16.1.tgz";
        sha512 = "64i+Uw3otrndfq5kaoGNoY7pvOhSsjFEN4bdEFh80MWVk/dbgJfMv7VFDeCT8LxNAlEVhQmdVEbfE7X2nWNIIg==";
      };
    };
    "parent-module-1.0.1" = {
      name = "parent-module";
      packageName = "parent-module";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parent-module/-/parent-module-1.0.1.tgz";
        sha512 = "GQ2EWRpQV8/o+Aw8YqtfZZPfNRWZYkbidE9k5rpl/hC3vtHHBfGm2Ifi6qWV+coDGkrUKZAxE3Lot5kcsRlh+g==";
      };
    };
    "parse-json-5.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-5.2.0.tgz";
        sha512 = "ayCKvm/phCGxOkYRSCM82iDwct8/EonSEgCSxWxD7ve6jHggsFl4fZVQBPRNgQoKiuV/odhFrGzQXZwbifC8Rg==";
      };
    };
    "parse5-6.0.1" = {
      name = "parse5";
      packageName = "parse5";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse5/-/parse5-6.0.1.tgz";
        sha512 = "Ofn/CTFzRGTTxwpNEs9PP93gXShHcTq255nzRYSKe8AkVpZY7e1fpmTfOyoIvjP5HG7Z2ZM7VS9PPhQGW2pOpw==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-type-4.0.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-4.0.0.tgz";
        sha512 = "gDKb8aZMDeD/tZWs9P6+q0J9Mwkdl6xMV8TjnGP3qJVJ06bdMgkbBlLU8IdfOsIsFz2BW1rNVT3XuNEl8zPAvw==";
      };
    };
    "picomatch-2.3.0" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.0.tgz";
        sha512 = "lY1Q/PiJGC2zOv/z391WOTD+Z02bCgsFfvxoXXf6h7kv9o+WmsmzYqrAwY63sNgOxE4xEdq0WyUnXfKeBrSvYw==";
      };
    };
    "pkcs7-1.0.4" = {
      name = "pkcs7";
      packageName = "pkcs7";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkcs7/-/pkcs7-1.0.4.tgz";
        sha512 = "afRERtHn54AlwaF2/+LFszyAANTCggGilmcmILUzEjvs3XgFZT+xE6+QWQcAGmu4xajy+Xtj7acLOPdx5/eXWQ==";
      };
    };
    "postcss-8.3.5" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.3.5.tgz";
        sha512 = "NxTuJocUhYGsMiMFHDUkmjSKT3EdH4/WbGF6GCi1NDGk+vbcUTun4fpbOqaPtD8IIsztA2ilZm2DhYCuyN58gA==";
      };
    };
    "postcss-calc-8.0.0" = {
      name = "postcss-calc";
      packageName = "postcss-calc";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-calc/-/postcss-calc-8.0.0.tgz";
        sha512 = "5NglwDrcbiy8XXfPM11F3HeC6hoT9W7GUH/Zi5U/p7u3Irv4rHhdDcIZwG0llHXV4ftsBjpfWMXAnXNl4lnt8g==";
      };
    };
    "postcss-colormin-5.2.0" = {
      name = "postcss-colormin";
      packageName = "postcss-colormin";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-colormin/-/postcss-colormin-5.2.0.tgz";
        sha512 = "+HC6GfWU3upe5/mqmxuqYZ9B2Wl4lcoUUNkoaX59nEWV4EtADCMiBqui111Bu8R8IvaZTmqmxrqOAqjbHIwXPw==";
      };
    };
    "postcss-convert-values-5.0.1" = {
      name = "postcss-convert-values";
      packageName = "postcss-convert-values";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-convert-values/-/postcss-convert-values-5.0.1.tgz";
        sha512 = "C3zR1Do2BkKkCgC0g3sF8TS0koF2G+mN8xxayZx3f10cIRmTaAnpgpRQZjNekTZxM2ciSPoh2IWJm0VZx8NoQg==";
      };
    };
    "postcss-discard-comments-5.0.1" = {
      name = "postcss-discard-comments";
      packageName = "postcss-discard-comments";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-comments/-/postcss-discard-comments-5.0.1.tgz";
        sha512 = "lgZBPTDvWrbAYY1v5GYEv8fEO/WhKOu/hmZqmCYfrpD6eyDWWzAOsl2rF29lpvziKO02Gc5GJQtlpkTmakwOWg==";
      };
    };
    "postcss-discard-duplicates-5.0.1" = {
      name = "postcss-discard-duplicates";
      packageName = "postcss-discard-duplicates";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-duplicates/-/postcss-discard-duplicates-5.0.1.tgz";
        sha512 = "svx747PWHKOGpAXXQkCc4k/DsWo+6bc5LsVrAsw+OU+Ibi7klFZCyX54gjYzX4TH+f2uzXjRviLARxkMurA2bA==";
      };
    };
    "postcss-discard-empty-5.0.1" = {
      name = "postcss-discard-empty";
      packageName = "postcss-discard-empty";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-empty/-/postcss-discard-empty-5.0.1.tgz";
        sha512 = "vfU8CxAQ6YpMxV2SvMcMIyF2LX1ZzWpy0lqHDsOdaKKLQVQGVP1pzhrI9JlsO65s66uQTfkQBKBD/A5gp9STFw==";
      };
    };
    "postcss-discard-overridden-5.0.1" = {
      name = "postcss-discard-overridden";
      packageName = "postcss-discard-overridden";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-overridden/-/postcss-discard-overridden-5.0.1.tgz";
        sha512 = "Y28H7y93L2BpJhrdUR2SR2fnSsT+3TVx1NmVQLbcnZWwIUpJ7mfcTC6Za9M2PG6w8j7UQRfzxqn8jU2VwFxo3Q==";
      };
    };
    "postcss-merge-longhand-5.0.2" = {
      name = "postcss-merge-longhand";
      packageName = "postcss-merge-longhand";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-merge-longhand/-/postcss-merge-longhand-5.0.2.tgz";
        sha512 = "BMlg9AXSI5G9TBT0Lo/H3PfUy63P84rVz3BjCFE9e9Y9RXQZD3+h3YO1kgTNsNJy7bBc1YQp8DmSnwLIW5VPcw==";
      };
    };
    "postcss-merge-rules-5.0.2" = {
      name = "postcss-merge-rules";
      packageName = "postcss-merge-rules";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-merge-rules/-/postcss-merge-rules-5.0.2.tgz";
        sha512 = "5K+Md7S3GwBewfB4rjDeol6V/RZ8S+v4B66Zk2gChRqLTCC8yjnHQ601omj9TKftS19OPGqZ/XzoqpzNQQLwbg==";
      };
    };
    "postcss-minify-font-values-5.0.1" = {
      name = "postcss-minify-font-values";
      packageName = "postcss-minify-font-values";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-font-values/-/postcss-minify-font-values-5.0.1.tgz";
        sha512 = "7JS4qIsnqaxk+FXY1E8dHBDmraYFWmuL6cgt0T1SWGRO5bzJf8sUoelwa4P88LEWJZweHevAiDKxHlofuvtIoA==";
      };
    };
    "postcss-minify-gradients-5.0.1" = {
      name = "postcss-minify-gradients";
      packageName = "postcss-minify-gradients";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-gradients/-/postcss-minify-gradients-5.0.1.tgz";
        sha512 = "odOwBFAIn2wIv+XYRpoN2hUV3pPQlgbJ10XeXPq8UY2N+9ZG42xu45lTn/g9zZ+d70NKSQD6EOi6UiCMu3FN7g==";
      };
    };
    "postcss-minify-params-5.0.1" = {
      name = "postcss-minify-params";
      packageName = "postcss-minify-params";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-params/-/postcss-minify-params-5.0.1.tgz";
        sha512 = "4RUC4k2A/Q9mGco1Z8ODc7h+A0z7L7X2ypO1B6V8057eVK6mZ6xwz6QN64nHuHLbqbclkX1wyzRnIrdZehTEHw==";
      };
    };
    "postcss-minify-selectors-5.1.0" = {
      name = "postcss-minify-selectors";
      packageName = "postcss-minify-selectors";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-selectors/-/postcss-minify-selectors-5.1.0.tgz";
        sha512 = "NzGBXDa7aPsAcijXZeagnJBKBPMYLaJJzB8CQh6ncvyl2sIndLVWfbcDi0SBjRWk5VqEjXvf8tYwzoKf4Z07og==";
      };
    };
    "postcss-nested-5.0.5" = {
      name = "postcss-nested";
      packageName = "postcss-nested";
      version = "5.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-nested/-/postcss-nested-5.0.5.tgz";
        sha512 = "GSRXYz5bccobpTzLQZXOnSOfKl6TwVr5CyAQJUPub4nuRJSOECK5AqurxVgmtxP48p0Kc/ndY/YyS1yqldX0Ew==";
      };
    };
    "postcss-normalize-charset-5.0.1" = {
      name = "postcss-normalize-charset";
      packageName = "postcss-normalize-charset";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-charset/-/postcss-normalize-charset-5.0.1.tgz";
        sha512 = "6J40l6LNYnBdPSk+BHZ8SF+HAkS4q2twe5jnocgd+xWpz/mx/5Sa32m3W1AA8uE8XaXN+eg8trIlfu8V9x61eg==";
      };
    };
    "postcss-normalize-display-values-5.0.1" = {
      name = "postcss-normalize-display-values";
      packageName = "postcss-normalize-display-values";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-display-values/-/postcss-normalize-display-values-5.0.1.tgz";
        sha512 = "uupdvWk88kLDXi5HEyI9IaAJTE3/Djbcrqq8YgjvAVuzgVuqIk3SuJWUisT2gaJbZm1H9g5k2w1xXilM3x8DjQ==";
      };
    };
    "postcss-normalize-positions-5.0.1" = {
      name = "postcss-normalize-positions";
      packageName = "postcss-normalize-positions";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-positions/-/postcss-normalize-positions-5.0.1.tgz";
        sha512 = "rvzWAJai5xej9yWqlCb1OWLd9JjW2Ex2BCPzUJrbaXmtKtgfL8dBMOOMTX6TnvQMtjk3ei1Lswcs78qKO1Skrg==";
      };
    };
    "postcss-normalize-repeat-style-5.0.1" = {
      name = "postcss-normalize-repeat-style";
      packageName = "postcss-normalize-repeat-style";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-repeat-style/-/postcss-normalize-repeat-style-5.0.1.tgz";
        sha512 = "syZ2itq0HTQjj4QtXZOeefomckiV5TaUO6ReIEabCh3wgDs4Mr01pkif0MeVwKyU/LHEkPJnpwFKRxqWA/7O3w==";
      };
    };
    "postcss-normalize-string-5.0.1" = {
      name = "postcss-normalize-string";
      packageName = "postcss-normalize-string";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-string/-/postcss-normalize-string-5.0.1.tgz";
        sha512 = "Ic8GaQ3jPMVl1OEn2U//2pm93AXUcF3wz+OriskdZ1AOuYV25OdgS7w9Xu2LO5cGyhHCgn8dMXh9bO7vi3i9pA==";
      };
    };
    "postcss-normalize-timing-functions-5.0.1" = {
      name = "postcss-normalize-timing-functions";
      packageName = "postcss-normalize-timing-functions";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-timing-functions/-/postcss-normalize-timing-functions-5.0.1.tgz";
        sha512 = "cPcBdVN5OsWCNEo5hiXfLUnXfTGtSFiBU9SK8k7ii8UD7OLuznzgNRYkLZow11BkQiiqMcgPyh4ZqXEEUrtQ1Q==";
      };
    };
    "postcss-normalize-unicode-5.0.1" = {
      name = "postcss-normalize-unicode";
      packageName = "postcss-normalize-unicode";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-unicode/-/postcss-normalize-unicode-5.0.1.tgz";
        sha512 = "kAtYD6V3pK0beqrU90gpCQB7g6AOfP/2KIPCVBKJM2EheVsBQmx/Iof+9zR9NFKLAx4Pr9mDhogB27pmn354nA==";
      };
    };
    "postcss-normalize-url-5.0.2" = {
      name = "postcss-normalize-url";
      packageName = "postcss-normalize-url";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-url/-/postcss-normalize-url-5.0.2.tgz";
        sha512 = "k4jLTPUxREQ5bpajFQZpx8bCF2UrlqOTzP9kEqcEnOfwsRshWs2+oAFIHfDQB8GO2PaUaSE0NlTAYtbluZTlHQ==";
      };
    };
    "postcss-normalize-whitespace-5.0.1" = {
      name = "postcss-normalize-whitespace";
      packageName = "postcss-normalize-whitespace";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-whitespace/-/postcss-normalize-whitespace-5.0.1.tgz";
        sha512 = "iPklmI5SBnRvwceb/XH568yyzK0qRVuAG+a1HFUsFRf11lEJTiQQa03a4RSCQvLKdcpX7XsI1Gen9LuLoqwiqA==";
      };
    };
    "postcss-ordered-values-5.0.2" = {
      name = "postcss-ordered-values";
      packageName = "postcss-ordered-values";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-ordered-values/-/postcss-ordered-values-5.0.2.tgz";
        sha512 = "8AFYDSOYWebJYLyJi3fyjl6CqMEG/UVworjiyK1r573I56kb3e879sCJLGvR3merj+fAdPpVplXKQZv+ey6CgQ==";
      };
    };
    "postcss-reduce-initial-5.0.1" = {
      name = "postcss-reduce-initial";
      packageName = "postcss-reduce-initial";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-reduce-initial/-/postcss-reduce-initial-5.0.1.tgz";
        sha512 = "zlCZPKLLTMAqA3ZWH57HlbCjkD55LX9dsRyxlls+wfuRfqCi5mSlZVan0heX5cHr154Dq9AfbH70LyhrSAezJw==";
      };
    };
    "postcss-reduce-transforms-5.0.1" = {
      name = "postcss-reduce-transforms";
      packageName = "postcss-reduce-transforms";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-reduce-transforms/-/postcss-reduce-transforms-5.0.1.tgz";
        sha512 = "a//FjoPeFkRuAguPscTVmRQUODP+f3ke2HqFNgGPwdYnpeC29RZdCBvGRGTsKpMURb/I3p6jdKoBQ2zI+9Q7kA==";
      };
    };
    "postcss-selector-parser-6.0.6" = {
      name = "postcss-selector-parser";
      packageName = "postcss-selector-parser";
      version = "6.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-6.0.6.tgz";
        sha512 = "9LXrvaaX3+mcv5xkg5kFwqSzSH1JIObIx51PrndZwlmznwXRfxMddDvo9gve3gVR8ZTKgoFDdWkbRFmEhT4PMg==";
      };
    };
    "postcss-svgo-5.0.2" = {
      name = "postcss-svgo";
      packageName = "postcss-svgo";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-svgo/-/postcss-svgo-5.0.2.tgz";
        sha512 = "YzQuFLZu3U3aheizD+B1joQ94vzPfE6BNUcSYuceNxlVnKKsOtdo6hL9/zyC168Q8EwfLSgaDSalsUGa9f2C0A==";
      };
    };
    "postcss-unique-selectors-5.0.1" = {
      name = "postcss-unique-selectors";
      packageName = "postcss-unique-selectors";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-unique-selectors/-/postcss-unique-selectors-5.0.1.tgz";
        sha512 = "gwi1NhHV4FMmPn+qwBNuot1sG1t2OmacLQ/AX29lzyggnjd+MnVD5uqQmpXO3J17KGL2WAxQruj1qTd3H0gG/w==";
      };
    };
    "postcss-url-10.1.3" = {
      name = "postcss-url";
      packageName = "postcss-url";
      version = "10.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-url/-/postcss-url-10.1.3.tgz";
        sha512 = "FUzyxfI5l2tKmXdYc6VTu3TWZsInayEKPbiyW+P6vmmIrrb4I6CGX0BFoewgYHLK+oIL5FECEK02REYRpBvUCw==";
      };
    };
    "postcss-value-parser-4.1.0" = {
      name = "postcss-value-parser";
      packageName = "postcss-value-parser";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-value-parser/-/postcss-value-parser-4.1.0.tgz";
        sha512 = "97DXOFbQJhk71ne5/Mt6cOu6yxsSfM0QGQyl0L25Gca4yGWEGJaig7l7gbCX623VqTBNGLRLaVUCnNkcedlRSQ==";
      };
    };
    "process-0.11.10" = {
      name = "process";
      packageName = "process";
      version = "0.11.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
        sha1 = "7332300e840161bda3e69a1d1d91a7d4bc16f182";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "regenerator-runtime-0.13.7" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.7.tgz";
        sha512 = "a54FxoJDIr27pgf7IgeQGxmqUNYrcV338lf/6gH456HZ/PhX+5BcwHXG9ajESmwe6WRO0tAzRUrRmNONWgkrew==";
      };
    };
    "resolve-from-4.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-4.0.0.tgz";
        sha512 = "pb/MYmXstAkysRFx8piNI1tGFNQIFA3vkE3Gq4EuA1dF6gHp/+vgZqsCGJapvy8N3Q+4o7FwvquPJcnZ7RYy4g==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "rgb-regex-1.0.1" = {
      name = "rgb-regex";
      packageName = "rgb-regex";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rgb-regex/-/rgb-regex-1.0.1.tgz";
        sha1 = "c0e0d6882df0e23be254a475e8edd41915feaeb1";
      };
    };
    "rgba-regex-1.0.0" = {
      name = "rgba-regex";
      packageName = "rgba-regex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rgba-regex/-/rgba-regex-1.0.0.tgz";
        sha1 = "43374e2e2ca0968b0ef1523460b7d730ff22eeb3";
      };
    };
    "rimraf-2.7.1" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.7.1.tgz";
        sha512 = "uWjbaKIK3T1OSVptzX7Nl6PvQ3qAGtKEtVRjRuazjfL3Bx5eI409VZSqgND+4UNnmzLVdPj9FqFJNPqBZFve4w==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "rust-result-1.0.0" = {
      name = "rust-result";
      packageName = "rust-result";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rust-result/-/rust-result-1.0.0.tgz";
        sha1 = "34c75b2e6dc39fe5875e5bdec85b5e0f91536f72";
      };
    };
    "safe-json-parse-4.0.0" = {
      name = "safe-json-parse";
      packageName = "safe-json-parse";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-json-parse/-/safe-json-parse-4.0.0.tgz";
        sha1 = "7c0f578cfccd12d33a71c0e05413e2eca171eaac";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "servor-4.0.2" = {
      name = "servor";
      packageName = "servor";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/servor/-/servor-4.0.2.tgz";
        sha512 = "MlmQ5Ntv4jDYUN060x/KEmN7emvIqKMZ9OkM+nY8Bf2+KkyLmGsTqWLyAN2cZr5oESAcH00UanUyyrlS1LRjFw==";
      };
    };
    "slash-3.0.0" = {
      name = "slash";
      packageName = "slash";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/slash/-/slash-3.0.0.tgz";
        sha512 = "g9Q1haeby36OSStwb4ntCGGGaKsaVSjQ68fBxoQcutl5fS1vuY18H3wSt3jFyFtrkx+Kz0V1G85A4MyAdDMi2Q==";
      };
    };
    "source-map-0.1.34" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.1.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.1.34.tgz";
        sha1 = "a7cfe89aec7b1682c3b198d0acfb47d7d090566b";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-js-0.6.2" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-0.6.2.tgz";
        sha512 = "/3GptzWzu0+0MBQFrDKzw/DvvMTUORvgY6k6jd/VS6iCR4RDTKWH6v6WPwQoUO8667uQEf9Oe38DxAYWY5F/Ug==";
      };
    };
    "stable-0.1.8" = {
      name = "stable";
      packageName = "stable";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/stable/-/stable-0.1.8.tgz";
        sha512 = "ji9qxRnOVfcuLDySj9qzhGSEFVobyt1kIOSkj1qZzYLzq7Tos/oUUWvotUPQLlrsidqsK6tBH89Bc9kL5zHA6w==";
      };
    };
    "stylehacks-5.0.1" = {
      name = "stylehacks";
      packageName = "stylehacks";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylehacks/-/stylehacks-5.0.1.tgz";
        sha512 = "Es0rVnHIqbWzveU1b24kbw92HsebBepxfcqe5iix7t9j0PQqhs0IxXVXv0pY2Bxa08CgMkzD6OWql7kbGOuEdA==";
      };
    };
    "subscriptions-transport-ws-0.9.19" = {
      name = "subscriptions-transport-ws";
      packageName = "subscriptions-transport-ws";
      version = "0.9.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/subscriptions-transport-ws/-/subscriptions-transport-ws-0.9.19.tgz";
        sha512 = "dxdemxFFB0ppCLg10FTtRqH/31FNRL1y1BQv8209MK5I4CwALb7iihQg+7p65lFcIl8MHatINWBLOqpgU4Kyyw==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "svgo-2.3.0" = {
      name = "svgo";
      packageName = "svgo";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/svgo/-/svgo-2.3.0.tgz";
        sha512 = "fz4IKjNO6HDPgIQxu4IxwtubtbSfGEAJUq/IXyTPIkGhWck/faiiwfkvsB8LnBkKLvSoyNNIY6d13lZprJMc9Q==";
      };
    };
    "symbol-observable-1.2.0" = {
      name = "symbol-observable";
      packageName = "symbol-observable";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol-observable/-/symbol-observable-1.2.0.tgz";
        sha512 = "e900nM8RRtGhlV36KGEU9k65K3mPb1WV70OdjfxlG2EAuM1noi/E/BaW/uMhL7bPEssK8QV57vN3esixjUvcXQ==";
      };
    };
    "symbol-observable-4.0.0" = {
      name = "symbol-observable";
      packageName = "symbol-observable";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/symbol-observable/-/symbol-observable-4.0.0.tgz";
        sha512 = "b19dMThMV4HVFynSAM1++gBHAbk2Tc/osgLIBZMKsyqh34jb2e8Os7T6ZW/Bt3pJFdBTd2JwAnAAEQV7rSNvcQ==";
      };
    };
    "thenify-3.3.1" = {
      name = "thenify";
      packageName = "thenify";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/thenify/-/thenify-3.3.1.tgz";
        sha512 = "RVZSIV5IG10Hk3enotrhvz0T9em6cyHBLkH/YAZuKqd8hRkKhSfCGIcP2KUY0EPxndzANBmNllzWPwak+bheSw==";
      };
    };
    "thenify-all-1.6.0" = {
      name = "thenify-all";
      packageName = "thenify-all";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/thenify-all/-/thenify-all-1.6.0.tgz";
        sha1 = "1a1918d402d8fc3f98fbf234db0bcc8cc10e9726";
      };
    };
    "timsort-0.3.0" = {
      name = "timsort";
      packageName = "timsort";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/timsort/-/timsort-0.3.0.tgz";
        sha1 = "405411a8e7e6339fe64db9a234de11dc31e02bd4";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "ts-invariant-0.7.5" = {
      name = "ts-invariant";
      packageName = "ts-invariant";
      version = "0.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-invariant/-/ts-invariant-0.7.5.tgz";
        sha512 = "qfVyqTYWEqADMtncLqwpUdMjMSXnsqOeqGtj1LeJNFDjz8oqZ1YxLEp29YCOq65z0LgEiERqQ8ThVjnfibJNpg==";
      };
    };
    "tslib-1.14.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.14.1.tgz";
        sha512 = "Xni35NKzjgMrwevysHTCArtLDpPvye8zV/0E4EyYn43P7/7qvQwPh9BGkHewbMulVntbigmcT7rdX3BNo9wRJg==";
      };
    };
    "tslib-2.3.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.3.0.tgz";
        sha512 = "N82ooyxVNm6h1riLCoyS9e3fuJ3AMG2zIZs2Gd1ATcSFjSA23Q0fzjjZeh0jbJvWVDZ0cJT8yaNNaaXHzueNjg==";
      };
    };
    "uglify-js-2.4.24" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "2.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-2.4.24.tgz";
        sha1 = "fad5755c1e1577658bb06ff9ab6e548c95bebd6e";
      };
    };
    "uglify-to-browserify-1.0.2" = {
      name = "uglify-to-browserify";
      packageName = "uglify-to-browserify";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-to-browserify/-/uglify-to-browserify-1.0.2.tgz";
        sha1 = "6e0924d6bda6b5afe349e39a6d632850a0f882b7";
      };
    };
    "uniqs-2.0.0" = {
      name = "uniqs";
      packageName = "uniqs";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uniqs/-/uniqs-2.0.0.tgz";
        sha1 = "ffede4b36b25290696e6e165d4a59edb998e6b02";
      };
    };
    "universalify-2.0.0" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.0.tgz";
        sha512 = "hAZsKq7Yy11Zu1DE0OzWjw7nnLZmJZYTDZZyEFHZdUhV8FkH5MCfoU1XMaxXovpyW5nq5scPqq0ZDP9Zyl04oQ==";
      };
    };
    "url-toolkit-2.2.2" = {
      name = "url-toolkit";
      packageName = "url-toolkit";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-toolkit/-/url-toolkit-2.2.2.tgz";
        sha512 = "l25w6Sy+Iy3/IbogunxhWwljPaDnqpiKvrQRoLBm6DfISco7NyRIS7Zf6+Oxhy1T8kHxWdwLND7ZZba6NjXMug==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "vendors-1.0.4" = {
      name = "vendors";
      packageName = "vendors";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vendors/-/vendors-1.0.4.tgz";
        sha512 = "/juG65kTL4Cy2su4P8HjtkTxk6VmJDiOPBufWniqQ6wknac6jNiXS9vU+hO3wgusiyqWlzTbVHi0dyJqRONg3w==";
      };
    };
    "video.js-7.12.3" = {
      name = "video.js";
      packageName = "video.js";
      version = "7.12.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/video.js/-/video.js-7.12.3.tgz";
        sha512 = "N/Cjj9hjlscD7S6dJZu0gZNZVOf1HyYtq6zK5UItGdJV16haBLjW+YABdgvZgcETqSmyqHBUUqQ2rNGSTr3z6w==";
      };
    };
    "videojs-1.0.0" = {
      name = "videojs";
      packageName = "videojs";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/videojs/-/videojs-1.0.0.tgz";
        sha1 = "503712e0b743b8f637c5422192692ac4a34b54be";
      };
    };
    "videojs-contrib-quality-levels-2.1.0" = {
      name = "videojs-contrib-quality-levels";
      packageName = "videojs-contrib-quality-levels";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/videojs-contrib-quality-levels/-/videojs-contrib-quality-levels-2.1.0.tgz";
        sha512 = "dqGQGbL9AFhucxki7Zh0c3kIhH0PAPcHEh6jUdRyaFCVeOuqnJrOYs/3wNtsokDdBdRf2Du2annpu4Z2XaSZRg==";
      };
    };
    "videojs-font-3.2.0" = {
      name = "videojs-font";
      packageName = "videojs-font";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/videojs-font/-/videojs-font-3.2.0.tgz";
        sha512 = "g8vHMKK2/JGorSfqAZQUmYYNnXmfec4MLhwtEFS+mMs2IDY398GLysy6BH6K+aS1KMNu/xWZ8Sue/X/mdQPliA==";
      };
    };
    "videojs-hls-quality-selector-1.1.4" = {
      name = "videojs-hls-quality-selector";
      packageName = "videojs-hls-quality-selector";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/videojs-hls-quality-selector/-/videojs-hls-quality-selector-1.1.4.tgz";
        sha512 = "wWAjlLQui02gp//t9KHGd3XnbYO7wdOptskh3ZYCrbl/5Lbkveqb9yBVjH4e0zIQBPvGdWPMcOeDukf8iuYeBw==";
      };
    };
    "videojs-vtt.js-0.15.3" = {
      name = "videojs-vtt.js";
      packageName = "videojs-vtt.js";
      version = "0.15.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/videojs-vtt.js/-/videojs-vtt.js-0.15.3.tgz";
        sha512 = "5FvVsICuMRx6Hd7H/Y9s9GDeEtYcXQWzGMS+sl4UX3t/zoHp3y+isSfIPRochnTH7h+Bh1ILyC639xy9Z6kPag==";
      };
    };
    "window-size-0.1.0" = {
      name = "window-size";
      packageName = "window-size";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/window-size/-/window-size-0.1.0.tgz";
        sha1 = "5438cd2ea93b202efa3a19fe8887aee7c94f9c9d";
      };
    };
    "wordwrap-0.0.2" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz";
        sha1 = "b79669bb42ecb409f83d583cad52ca17eaa1643f";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-7.5.0" = {
      name = "ws";
      packageName = "ws";
      version = "7.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.5.0.tgz";
        sha512 = "6ezXvzOZupqKj4jUqbQ9tXuJNo+BR2gU8fFRk3XCP3e0G6WT414u5ELe6Y0vtp7kmSJ3F7YWObSNr1ESsgi4vw==";
      };
    };
    "xmldom-0.5.0" = {
      name = "xmldom";
      packageName = "xmldom";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmldom/-/xmldom-0.5.0.tgz";
        sha512 = "Foaj5FXVzgn7xFzsKeNIde9g6aFBxTPi37iwsno8QvApmtg7KYrr+OPyRHcJF7dud2a5nGRBXK3n0dL62Gf7PA==";
      };
    };
    "xxhashjs-0.2.2" = {
      name = "xxhashjs";
      packageName = "xxhashjs";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xxhashjs/-/xxhashjs-0.2.2.tgz";
        sha512 = "AkTuIuVTET12tpsVIQo+ZU6f/qDmKuRUcjaqR+OIvm+aCBsZ95i7UVY5WJ9TMsSaZ0DA2WxoZ4acu0sPH+OKAw==";
      };
    };
    "yaml-1.10.2" = {
      name = "yaml";
      packageName = "yaml";
      version = "1.10.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-1.10.2.tgz";
        sha512 = "r3vXyErRCYJ7wg28yvBY5VSoAF8ZvlcW9/BwUzEtUsjvX/DKs24dIkuwjtuprwJJHsbyUbLApepYTR1BN4uHrg==";
      };
    };
    "yargs-3.5.4" = {
      name = "yargs";
      packageName = "yargs";
      version = "3.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-3.5.4.tgz";
        sha1 = "d8aff8f665e94c34bd259bdebd1bfaf0ddd35361";
      };
    };
    "zen-observable-0.8.15" = {
      name = "zen-observable";
      packageName = "zen-observable";
      version = "0.8.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/zen-observable/-/zen-observable-0.8.15.tgz";
        sha512 = "PQ2PC7R9rslx84ndNBZB/Dkv8V8fZEpk83RLgXtYd0fwUgEjseMn1Dgajh2x6S8QbZAFa9p2qVCEuYZNgve0dQ==";
      };
    };
    "zlib-browserify-0.0.1" = {
      name = "zlib-browserify";
      packageName = "zlib-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/zlib-browserify/-/zlib-browserify-0.0.1.tgz";
        sha1 = "4fa6a45d00dbc15f318a4afa1d9afc0258e176cc";
      };
    };
  };
  args = {
    name = "waasabi-live";
    packageName = "waasabi-live";
    version = "0.3.0";
    src = ./..;
    dependencies = [
      sources."@apollo/client-3.3.20"
      sources."@babel/code-frame-7.14.5"
      sources."@babel/helper-validator-identifier-7.14.5"
      sources."@babel/highlight-7.14.5"
      sources."@babel/runtime-7.14.6"
      sources."@graphql-typed-document-node/core-3.1.0"
      sources."@lit/reactive-element-1.0.0-rc.2"
      sources."@nodelib/fs.scandir-2.1.5"
      sources."@nodelib/fs.stat-2.0.5"
      sources."@nodelib/fs.walk-1.2.7"
      sources."@trysound/sax-0.1.1"
      sources."@types/parse-json-4.0.0"
      sources."@types/trusted-types-1.0.6"
      sources."@types/zen-observable-0.8.2"
      sources."@videojs/http-streaming-2.8.2"
      sources."@videojs/vhs-utils-3.0.2"
      sources."@videojs/xhr-2.5.1"
      (sources."@wry/context-0.6.0" // {
        dependencies = [
          sources."tslib-2.3.0"
        ];
      })
      (sources."@wry/equality-0.5.1" // {
        dependencies = [
          sources."tslib-2.3.0"
        ];
      })
      (sources."@wry/trie-0.3.0" // {
        dependencies = [
          sources."tslib-2.3.0"
        ];
      })
      sources."aes-decrypter-3.1.2"
      sources."alphanum-sort-1.0.2"
      sources."amdefine-1.0.1"
      sources."ansi-styles-3.2.1"
      sources."any-promise-1.3.0"
      sources."array-union-2.1.0"
      sources."async-0.2.10"
      sources."autoprefixer-10.2.6"
      sources."backo2-1.0.2"
      sources."balanced-match-1.0.2"
      sources."boolbase-1.0.0"
      sources."brace-expansion-1.1.11"
      sources."braces-3.0.2"
      sources."browserslist-4.16.6"
      sources."callsites-3.1.0"
      sources."camelcase-1.2.1"
      sources."caniuse-api-3.0.0"
      sources."caniuse-lite-1.0.30001239"
      sources."chalk-2.4.2"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."colord-2.0.1"
      sources."colorette-1.2.2"
      sources."commander-7.2.0"
      sources."concat-map-0.0.1"
      sources."concat-with-sourcemaps-1.1.0"
      sources."cosmiconfig-7.0.0"
      sources."css-color-names-1.0.1"
      sources."css-declaration-sorter-6.0.3"
      sources."css-select-3.1.2"
      sources."css-tree-1.1.3"
      sources."css-what-4.0.0"
      sources."cssesc-3.0.0"
      sources."cssnano-5.0.6"
      sources."cssnano-preset-default-5.1.3"
      sources."cssnano-utils-2.0.1"
      sources."csso-4.2.0"
      sources."cuint-0.2.2"
      sources."debug-4.3.1"
      sources."decamelize-1.2.0"
      sources."dir-glob-3.0.1"
      sources."dom-serializer-1.3.2"
      sources."dom-walk-0.1.2"
      sources."domelementtype-2.2.0"
      sources."domhandler-4.2.0"
      sources."domutils-2.7.0"
      sources."dotenv-10.0.0"
      sources."electron-to-chromium-1.3.756"
      sources."entities-2.2.0"
      sources."error-ex-1.3.2"
      sources."esbuild-0.12.9"
      sources."escalade-3.1.1"
      sources."escape-string-regexp-1.0.5"
      sources."esmarked-2.1.1"
      sources."eventemitter3-3.1.2"
      sources."fast-glob-3.2.5"
      sources."fast-json-stable-stringify-2.1.0"
      sources."fastq-1.11.0"
      sources."fill-range-7.0.1"
      sources."fraction.js-4.1.1"
      sources."fs-extra-10.0.0"
      (sources."fs-promise-0.5.0" // {
        dependencies = [
          sources."fs-extra-0.26.7"
          sources."jsonfile-2.4.0"
        ];
      })
      sources."fs.realpath-1.0.0"
      sources."glob-7.1.7"
      sources."glob-parent-5.1.2"
      sources."global-4.4.0"
      sources."globby-11.0.4"
      sources."graceful-fs-4.2.6"
      sources."graphql-15.5.1"
      (sources."graphql-tag-2.12.4" // {
        dependencies = [
          sources."tslib-2.3.0"
        ];
      })
      sources."grunt-contrib-uglify-0.2.7"
      sources."grunt-lib-contrib-0.6.1"
      sources."has-flag-3.0.0"
      sources."hex-color-regex-1.1.0"
      sources."hoist-non-react-statics-3.3.2"
      sources."hsl-regex-1.0.0"
      sources."hsla-regex-1.0.0"
      sources."html-prettify-1.0.3"
      sources."ignore-5.1.8"
      sources."import-fresh-3.3.0"
      sources."individual-2.0.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-absolute-url-3.0.3"
      sources."is-arrayish-0.2.1"
      (sources."is-color-stop-1.1.0" // {
        dependencies = [
          sources."css-color-names-0.0.4"
        ];
      })
      sources."is-extglob-2.1.1"
      sources."is-function-1.0.2"
      sources."is-glob-4.0.1"
      sources."is-number-7.0.0"
      sources."is-resolvable-1.1.0"
      sources."iterall-1.3.0"
      sources."js-tokens-4.0.0"
      sources."json-parse-even-better-errors-2.3.1"
      sources."jsonfile-6.1.0"
      sources."karma-safaritechpreview-launcher-0.0.6"
      sources."keycode-2.2.0"
      sources."klaw-1.3.1"
      sources."lines-and-columns-1.1.6"
      sources."lit-2.0.0-rc.2"
      sources."lit-element-3.0.0-rc.2"
      sources."lit-html-2.0.0-rc.3"
      (sources."lit-ntml-2.18.2" // {
        dependencies = [
          sources."tslib-2.3.0"
        ];
      })
      sources."lodash.memoize-4.1.2"
      sources."lodash.uniq-4.5.0"
      sources."loose-envify-1.4.0"
      sources."m3u8-parser-4.7.0"
      sources."make-dir-3.1.0"
      sources."marcosc-async-3.0.5"
      sources."mdn-data-2.0.14"
      sources."merge2-1.4.1"
      sources."micromatch-4.0.4"
      sources."mime-2.5.2"
      sources."min-document-2.19.0"
      sources."minimatch-3.0.4"
      sources."mpd-parser-0.16.0"
      sources."ms-2.1.2"
      sources."mux.js-5.11.0"
      sources."mz-2.7.0"
      sources."nanoid-3.1.23"
      sources."node-releases-1.1.73"
      sources."normalize-range-0.1.2"
      sources."normalize-url-6.1.0"
      sources."nth-check-2.0.0"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."optimism-0.16.1"
      sources."parent-module-1.0.1"
      sources."parse-json-5.2.0"
      sources."parse5-6.0.1"
      sources."path-is-absolute-1.0.1"
      sources."path-type-4.0.0"
      sources."picomatch-2.3.0"
      sources."pkcs7-1.0.4"
      sources."postcss-8.3.5"
      sources."postcss-calc-8.0.0"
      sources."postcss-colormin-5.2.0"
      sources."postcss-convert-values-5.0.1"
      sources."postcss-discard-comments-5.0.1"
      sources."postcss-discard-duplicates-5.0.1"
      sources."postcss-discard-empty-5.0.1"
      sources."postcss-discard-overridden-5.0.1"
      sources."postcss-merge-longhand-5.0.2"
      sources."postcss-merge-rules-5.0.2"
      sources."postcss-minify-font-values-5.0.1"
      sources."postcss-minify-gradients-5.0.1"
      sources."postcss-minify-params-5.0.1"
      sources."postcss-minify-selectors-5.1.0"
      sources."postcss-nested-5.0.5"
      sources."postcss-normalize-charset-5.0.1"
      sources."postcss-normalize-display-values-5.0.1"
      sources."postcss-normalize-positions-5.0.1"
      sources."postcss-normalize-repeat-style-5.0.1"
      sources."postcss-normalize-string-5.0.1"
      sources."postcss-normalize-timing-functions-5.0.1"
      sources."postcss-normalize-unicode-5.0.1"
      sources."postcss-normalize-url-5.0.2"
      sources."postcss-normalize-whitespace-5.0.1"
      sources."postcss-ordered-values-5.0.2"
      sources."postcss-reduce-initial-5.0.1"
      sources."postcss-reduce-transforms-5.0.1"
      sources."postcss-selector-parser-6.0.6"
      sources."postcss-svgo-5.0.2"
      sources."postcss-unique-selectors-5.0.1"
      sources."postcss-url-10.1.3"
      sources."postcss-value-parser-4.1.0"
      sources."process-0.11.10"
      sources."prop-types-15.7.2"
      sources."queue-microtask-1.2.3"
      sources."react-is-16.13.1"
      sources."regenerator-runtime-0.13.7"
      sources."resolve-from-4.0.0"
      sources."reusify-1.0.4"
      sources."rgb-regex-1.0.1"
      sources."rgba-regex-1.0.0"
      sources."rimraf-2.7.1"
      sources."run-parallel-1.2.0"
      sources."rust-result-1.0.0"
      sources."safe-json-parse-4.0.0"
      sources."semver-6.3.0"
      sources."servor-4.0.2"
      sources."slash-3.0.0"
      sources."source-map-0.6.1"
      sources."source-map-js-0.6.2"
      sources."stable-0.1.8"
      sources."stylehacks-5.0.1"
      (sources."subscriptions-transport-ws-0.9.19" // {
        dependencies = [
          sources."symbol-observable-1.2.0"
        ];
      })
      sources."supports-color-5.5.0"
      (sources."svgo-2.3.0" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."chalk-4.1.1"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
          sources."has-flag-4.0.0"
          sources."supports-color-7.2.0"
        ];
      })
      sources."symbol-observable-4.0.0"
      sources."thenify-3.3.1"
      sources."thenify-all-1.6.0"
      sources."timsort-0.3.0"
      sources."to-regex-range-5.0.1"
      (sources."ts-invariant-0.7.5" // {
        dependencies = [
          sources."tslib-2.3.0"
        ];
      })
      sources."tslib-1.14.1"
      (sources."uglify-js-2.4.24" // {
        dependencies = [
          sources."source-map-0.1.34"
        ];
      })
      sources."uglify-to-browserify-1.0.2"
      sources."uniqs-2.0.0"
      sources."universalify-2.0.0"
      sources."url-toolkit-2.2.2"
      sources."util-deprecate-1.0.2"
      sources."vendors-1.0.4"
      sources."video.js-7.12.3"
      sources."videojs-1.0.0"
      sources."videojs-contrib-quality-levels-2.1.0"
      sources."videojs-font-3.2.0"
      sources."videojs-hls-quality-selector-1.1.4"
      sources."videojs-vtt.js-0.15.3"
      sources."window-size-0.1.0"
      sources."wordwrap-0.0.2"
      sources."wrappy-1.0.2"
      sources."ws-7.5.0"
      sources."xmldom-0.5.0"
      sources."xxhashjs-0.2.2"
      sources."yaml-1.10.2"
      sources."yargs-3.5.4"
      sources."zen-observable-0.8.15"
      sources."zlib-browserify-0.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Waasabi live event streaming experience";
      homepage = "https://github.com/baytechc/waasabi-live#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
